version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    restart: always
